version: 2
jobs:
    build:
        working_directory: ~/jetti.cli
        docker: # run the steps with Docker
            - image: circleci/node:14.11.0
        steps:
            # Checkout and build the code
            - type: checkout
            - run: echo "registry=https://registry.npmjs.org/" > ~/.npmrc
            - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
             # Setup the credentials to publish the shared repo
            - run: git config --global user.email "circleci@circleci"
            - run: git config --global user.name "CircleCI"
            - run: yarn
            - deploy:
                name: Deploy Master
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        cd ~/jetti.cli
                        npm publish
                        curl -X POST -d '{"repo": "@jetti/jetti.cli"}' "${WEBHOOK}"
                    fi
            # Run build error notification
            - run:
                name: Fail notification
                command: |-
                    curl -d '{"repo": "@jetti/jetti.cli"}' -X POST "${WEBHOOK}"
                when: on_fail
